import { useEffect } from 'react'
import Head from 'next/head'

export default function Home() {

  useEffect(() => {
    setTimeInClock()
  }, [])

  const setTimeInClock = () => {
    let date, hr, min, sec;
    let hour = document.getElementById("hour");
    let minute = document.getElementById("min");
    let second = document.getElementById("sec");
    setInterval(() => {
      date = new Date(); //object of date()
      min = date.getMinutes() * 6;
      hr = 30 * date.getHours() + date.getMinutes() / 2;
      sec = date.getSeconds() * 6;
      hour.style.transform = `rotate(${hr}deg)`;
      minute.style.transform = `rotate(${min}deg)`;
      second.style.transform = `rotate(${sec}deg)`;
    }, 1000);
  }

  return (
    <div className="container">
      <Head>
        <title>Analog Clock Under Process</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="main_container">

          <div className="forksparent">
            <div className="forks one"></div>
            <div className="forks two"></div>
            <div className="forks three"></div>
            <div className="forks four"></div>
            <div className="forks five"></div>
            <div className="forks six"></div>
            <div className="blankcircle"></div>
            <div id="hour"></div>
            <div id="min"></div>
            <div id="sec"></div>
            <div className="circle"></div>
            <div className="glass"></div>
          </div>
        </div>
      </main>
    </div>
  )
}
